modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "londonunderground"
version = "${version}"
displayName = "MTR Lunjiao Underground Addon"
authors = "Chris Herbert, Benjamin Wyatt, SteveNotSet"
description = "A London Underground Addon for the Minecraft Transit Railway Mod, modified by SteveNotSet.\nRemoved all the stupid things."
logoFile = "icon.png"

[[dependencies.londonunderground]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.londonunderground]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.londonunderground]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.londonunderground]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
