# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.3, 1.19.4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew setupLibrary -PbuildVersion="${{ matrix.minecraft }}"
      - name: Build ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew build -PbuildVersion="${{ matrix.minecraft }}"
      - name: Capture release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MTR-Lunjiao-Underground-${{ matrix.minecraft }}
          path: build/release/*-${{ matrix.minecraft }}-*.jar
